data = {
		'OV, VK': {
                'Идентификатор проекта':[BuiltInCategory.OST_ProjectInformation],
                'Наименование проекта':[BuiltInCategory.OST_ProjectInformation],
                'Идентификатор объекта':[BuiltInCategory.OST_ProjectInformation],
                'Наименование объекта':[BuiltInCategory.OST_ProjectInformation],
        		'Идентификатор зоны работы': [
	                                        BuiltInCategory.OST_DuctAccessory,
	                                        BuiltInCategory.OST_PipeAccessory,
	                                        BuiltInCategory.OST_DuctCurves,
	                                        BuiltInCategory.OST_DuctTerminal,
                                            BuiltInCategory.OST_FlexPipeCurves,
                                            BuiltInCategory.OST_FlexDuctCurves,
											BuiltInCategory.OST_MechanicalEquipment,
                                            BuiltInCategory.OST_DuctSystem,
                                            BuiltInCategory.OST_PlumbingFixtures,
	                                        BuiltInCategory.OST_DuctFitting,
	                                        BuiltInCategory.OST_PipeFitting,
                                            BuiltInCategory.OST_PipingSystem,
                                        	BuiltInCategory.OST_PipeCurves,],
                'Наименование зоны работы': [
											BuiltInCategory.OST_DuctAccessory,
	                                        BuiltInCategory.OST_PipeAccessory,
	                                        BuiltInCategory.OST_DuctCurves,
	                                        BuiltInCategory.OST_DuctTerminal,
                                            BuiltInCategory.OST_FlexPipeCurves,
                                            BuiltInCategory.OST_FlexDuctCurves,
											BuiltInCategory.OST_MechanicalEquipment,
                                            BuiltInCategory.OST_DuctSystem,
                                            BuiltInCategory.OST_PlumbingFixtures,
	                                        BuiltInCategory.OST_DuctFitting,
	                                        BuiltInCategory.OST_PipeFitting,
                                            BuiltInCategory.OST_PipingSystem,
                                        	BuiltInCategory.OST_PipeCurves,],
				'Идентификатор вида работ': [
											BuiltInCategory.OST_DuctAccessory,
	                                        BuiltInCategory.OST_PipeAccessory,
	                                        BuiltInCategory.OST_DuctCurves,
	                                        BuiltInCategory.OST_DuctTerminal,
                                            BuiltInCategory.OST_FlexPipeCurves,
                                            BuiltInCategory.OST_FlexDuctCurves,
											BuiltInCategory.OST_MechanicalEquipment,
                                            BuiltInCategory.OST_DuctSystem,
                                            BuiltInCategory.OST_PlumbingFixtures,
	                                        BuiltInCategory.OST_DuctFitting,
	                                        BuiltInCategory.OST_PipeFitting,
                                            BuiltInCategory.OST_PipingSystem,
                                        	BuiltInCategory.OST_PipeCurves,],         
				'Наименование вида работ': [
											BuiltInCategory.OST_DuctAccessory,
	                                        BuiltInCategory.OST_PipeAccessory,
	                                        BuiltInCategory.OST_DuctCurves,
	                                        BuiltInCategory.OST_DuctTerminal,
                                            BuiltInCategory.OST_FlexPipeCurves,
                                            BuiltInCategory.OST_FlexDuctCurves,
											BuiltInCategory.OST_MechanicalEquipment,
                                            BuiltInCategory.OST_DuctSystem,
                                            BuiltInCategory.OST_PlumbingFixtures,
	                                        BuiltInCategory.OST_DuctFitting,
	                                        BuiltInCategory.OST_PipeFitting,
                                            BuiltInCategory.OST_PipingSystem,
                                        	BuiltInCategory.OST_PipeCurves,],
                'Идентификатор операции': [
											BuiltInCategory.OST_DuctAccessory,
	                                        BuiltInCategory.OST_PipeAccessory,
	                                        BuiltInCategory.OST_DuctCurves,
	                                        BuiltInCategory.OST_DuctTerminal,
                                            BuiltInCategory.OST_FlexPipeCurves,
                                            BuiltInCategory.OST_FlexDuctCurves,
											BuiltInCategory.OST_MechanicalEquipment,
                                            BuiltInCategory.OST_DuctSystem,
                                            BuiltInCategory.OST_PlumbingFixtures,
	                                        BuiltInCategory.OST_DuctFitting,
	                                        BuiltInCategory.OST_PipeFitting,
                                            BuiltInCategory.OST_PipingSystem,
                                        	BuiltInCategory.OST_PipeCurves,],
				'Наименование операции': [
											BuiltInCategory.OST_DuctAccessory,
	                                        BuiltInCategory.OST_PipeAccessory,
	                                        BuiltInCategory.OST_DuctCurves,
	                                        BuiltInCategory.OST_DuctTerminal,
                                            BuiltInCategory.OST_FlexPipeCurves,
                                            BuiltInCategory.OST_FlexDuctCurves,
											BuiltInCategory.OST_MechanicalEquipment,
                                            BuiltInCategory.OST_DuctSystem,
                                            BuiltInCategory.OST_PlumbingFixtures,
	                                        BuiltInCategory.OST_DuctFitting,
	                                        BuiltInCategory.OST_PipeFitting,
                                            BuiltInCategory.OST_PipingSystem,
                                        	BuiltInCategory.OST_PipeCurves,],
                'Код пакета работ': [
											BuiltInCategory.OST_DuctAccessory,
	                                        BuiltInCategory.OST_PipeAccessory,
	                                        BuiltInCategory.OST_DuctCurves,
	                                        BuiltInCategory.OST_DuctTerminal,
                                            BuiltInCategory.OST_FlexPipeCurves,
                                            BuiltInCategory.OST_FlexDuctCurves,
											BuiltInCategory.OST_MechanicalEquipment,
                                            BuiltInCategory.OST_DuctSystem,
                                            BuiltInCategory.OST_PlumbingFixtures,
	                                        BuiltInCategory.OST_DuctFitting,
	                                        BuiltInCategory.OST_PipeFitting,
                                            BuiltInCategory.OST_PipingSystem,
                                        	BuiltInCategory.OST_PipeCurves,],
                'Наименование пакета работ': [
											BuiltInCategory.OST_DuctAccessory,
	                                        BuiltInCategory.OST_PipeAccessory,
	                                        BuiltInCategory.OST_DuctCurves,
	                                        BuiltInCategory.OST_DuctTerminal,
                                            BuiltInCategory.OST_FlexPipeCurves,
                                            BuiltInCategory.OST_FlexDuctCurves,
											BuiltInCategory.OST_MechanicalEquipment,
                                            BuiltInCategory.OST_DuctSystem,
                                            BuiltInCategory.OST_PlumbingFixtures,
	                                        BuiltInCategory.OST_DuctFitting,
	                                        BuiltInCategory.OST_PipeFitting,
                                            BuiltInCategory.OST_PipingSystem,
                                        	BuiltInCategory.OST_PipeCurves,],
                'Код статьи затрат': [
											BuiltInCategory.OST_DuctAccessory,
	                                        BuiltInCategory.OST_PipeAccessory,
	                                        BuiltInCategory.OST_DuctCurves,
	                                        BuiltInCategory.OST_DuctTerminal,
                                            BuiltInCategory.OST_FlexPipeCurves,
                                            BuiltInCategory.OST_FlexDuctCurves,
											BuiltInCategory.OST_MechanicalEquipment,
                                            BuiltInCategory.OST_DuctSystem,
                                            BuiltInCategory.OST_PlumbingFixtures,
	                                        BuiltInCategory.OST_DuctFitting,
	                                        BuiltInCategory.OST_PipeFitting,
                                            BuiltInCategory.OST_PipingSystem,
                                        	BuiltInCategory.OST_PipeCurves,],
                'Идентификатор зоны': [
											BuiltInCategory.OST_DuctAccessory,
	                                        BuiltInCategory.OST_PipeAccessory,
	                                        BuiltInCategory.OST_DuctCurves,
	                                        BuiltInCategory.OST_DuctTerminal,
                                            BuiltInCategory.OST_FlexPipeCurves,
                                            BuiltInCategory.OST_FlexDuctCurves,
											BuiltInCategory.OST_MechanicalEquipment,
                                            BuiltInCategory.OST_DuctSystem,
                                            BuiltInCategory.OST_PlumbingFixtures,
	                                        BuiltInCategory.OST_DuctFitting,
	                                        BuiltInCategory.OST_PipeFitting,
                                            BuiltInCategory.OST_PipingSystem,
                                        	BuiltInCategory.OST_PipeCurves,],		
				'Наименование зоны': [
											BuiltInCategory.OST_DuctAccessory,
	                                        BuiltInCategory.OST_PipeAccessory,
	                                        BuiltInCategory.OST_DuctCurves,
	                                        BuiltInCategory.OST_DuctTerminal,
                                            BuiltInCategory.OST_FlexPipeCurves,
                                            BuiltInCategory.OST_FlexDuctCurves,
											BuiltInCategory.OST_MechanicalEquipment,
                                            BuiltInCategory.OST_DuctSystem,
                                            BuiltInCategory.OST_PlumbingFixtures,
	                                        BuiltInCategory.OST_DuctFitting,
	                                        BuiltInCategory.OST_PipeFitting,
                                            BuiltInCategory.OST_PipingSystem,
                                        	BuiltInCategory.OST_PipeCurves,],
                'Позиционное обозначение (тег)': [
											BuiltInCategory.OST_DuctAccessory,
	                                        BuiltInCategory.OST_PipeAccessory,
	                                        BuiltInCategory.OST_DuctCurves,
	                                        BuiltInCategory.OST_DuctTerminal,
                                            BuiltInCategory.OST_FlexPipeCurves,
                                            BuiltInCategory.OST_FlexDuctCurves,
											BuiltInCategory.OST_MechanicalEquipment,
                                            BuiltInCategory.OST_DuctSystem,
                                            BuiltInCategory.OST_PlumbingFixtures,
	                                        BuiltInCategory.OST_DuctFitting,
	                                        BuiltInCategory.OST_PipeFitting,
                                            BuiltInCategory.OST_PipingSystem,
                                        	BuiltInCategory.OST_PipeCurves,],
				'Идентификатор линии/участка': [
											BuiltInCategory.OST_DuctAccessory,
	                                        BuiltInCategory.OST_PipeAccessory,
	                                        BuiltInCategory.OST_DuctCurves,
	                                        BuiltInCategory.OST_DuctTerminal,
                                            BuiltInCategory.OST_FlexPipeCurves,
                                            BuiltInCategory.OST_FlexDuctCurves,
											BuiltInCategory.OST_MechanicalEquipment,
                                            BuiltInCategory.OST_DuctSystem,
                                            BuiltInCategory.OST_PlumbingFixtures,
	                                        BuiltInCategory.OST_DuctFitting,
	                                        BuiltInCategory.OST_PipeFitting,
                                            BuiltInCategory.OST_PipingSystem,
                                        	BuiltInCategory.OST_PipeCurves,],
				'Наименование линии/участка': [
											BuiltInCategory.OST_DuctAccessory,
	                                        BuiltInCategory.OST_PipeAccessory,
	                                        BuiltInCategory.OST_DuctCurves,
	                                        BuiltInCategory.OST_DuctTerminal,
                                            BuiltInCategory.OST_FlexPipeCurves,
                                            BuiltInCategory.OST_FlexDuctCurves,
											BuiltInCategory.OST_MechanicalEquipment,
                                            BuiltInCategory.OST_DuctSystem,
                                            BuiltInCategory.OST_PlumbingFixtures,
	                                        BuiltInCategory.OST_DuctFitting,
	                                        BuiltInCategory.OST_PipeFitting,
                                            BuiltInCategory.OST_PipingSystem,
                                        	BuiltInCategory.OST_PipeCurves,],
				'Код ТМЦ': [
											BuiltInCategory.OST_DuctAccessory,
	                                        BuiltInCategory.OST_PipeAccessory,
	                                        BuiltInCategory.OST_DuctCurves,
	                                        BuiltInCategory.OST_DuctTerminal,
                                            BuiltInCategory.OST_FlexPipeCurves,
                                            BuiltInCategory.OST_FlexDuctCurves,
											BuiltInCategory.OST_MechanicalEquipment,
                                            BuiltInCategory.OST_DuctSystem,
                                            BuiltInCategory.OST_PlumbingFixtures,
	                                        BuiltInCategory.OST_DuctFitting,
	                                        BuiltInCategory.OST_PipeFitting,
                                            BuiltInCategory.OST_PipingSystem,
                                        	BuiltInCategory.OST_PipeCurves,],
		},
		'AS': {
				'Идентификатор проекта':[BuiltInCategory.OST_ProjectInformation],
                'Наименование проекта':[BuiltInCategory.OST_ProjectInformation],
                'Идентификатор объекта':[BuiltInCategory.OST_ProjectInformation],
                'Наименование объекта':[BuiltInCategory.OST_ProjectInformation],
				'Идентификатор зоны работы': [
											BuiltInCategory.OST_Doors,
											BuiltInCategory.OST_StructuralFraming,
											BuiltInCategory.OST_Columns,
											BuiltInCategory.OST_Stairs,
											BuiltInCategory.OST_StructuralColumns,
											BuiltInCategory.OST_Windows,
											BuiltInCategory.OST_Ramps,
											BuiltInCategory.OST_Floors,
											BuiltInCategory.OST_Ceilings,
											BuiltInCategory.OST_ShaftOpening,
											BuiltInCategory.OST_Walls,],
				'Наименование зоны работы': [
											BuiltInCategory.OST_Doors,
											BuiltInCategory.OST_StructuralFraming,
											BuiltInCategory.OST_Columns,
											BuiltInCategory.OST_Stairs,
											BuiltInCategory.OST_StructuralColumns,
											BuiltInCategory.OST_Windows,
											BuiltInCategory.OST_Ramps,
											BuiltInCategory.OST_Floors,
											BuiltInCategory.OST_Ceilings,
											BuiltInCategory.OST_ShaftOpening,
											BuiltInCategory.OST_Walls,],
				'Идентификатор вида работ': [
											BuiltInCategory.OST_Doors,
											BuiltInCategory.OST_StructuralFraming,
											BuiltInCategory.OST_Columns,
											BuiltInCategory.OST_Stairs,
											BuiltInCategory.OST_StructuralColumns,
											BuiltInCategory.OST_Windows,
											BuiltInCategory.OST_Ramps,
											BuiltInCategory.OST_Floors,
											BuiltInCategory.OST_Ceilings,
											BuiltInCategory.OST_ShaftOpening,
											BuiltInCategory.OST_Walls,],
				'Наименование вида работ': [
											BuiltInCategory.OST_Doors,
											BuiltInCategory.OST_StructuralFraming,
											BuiltInCategory.OST_Columns,
											BuiltInCategory.OST_Stairs,
											BuiltInCategory.OST_StructuralColumns,
											BuiltInCategory.OST_Windows,
											BuiltInCategory.OST_Ramps,
											BuiltInCategory.OST_Floors,
											BuiltInCategory.OST_Ceilings,
											BuiltInCategory.OST_ShaftOpening,
											BuiltInCategory.OST_Walls,],
				'Идентификатор операции': [
											BuiltInCategory.OST_Doors,
											BuiltInCategory.OST_StructuralFraming,
											BuiltInCategory.OST_Columns,
											BuiltInCategory.OST_Stairs,
											BuiltInCategory.OST_StructuralColumns,
											BuiltInCategory.OST_Windows,
											BuiltInCategory.OST_Ramps,
											BuiltInCategory.OST_Floors,
											BuiltInCategory.OST_Ceilings,
											BuiltInCategory.OST_ShaftOpening,
											BuiltInCategory.OST_Walls,],
				'Наименование операции': [
											BuiltInCategory.OST_Doors,
											BuiltInCategory.OST_StructuralFraming,
											BuiltInCategory.OST_Columns,
											BuiltInCategory.OST_Stairs,
											BuiltInCategory.OST_StructuralColumns,
											BuiltInCategory.OST_Windows,
											BuiltInCategory.OST_Ramps,
											BuiltInCategory.OST_Floors,
											BuiltInCategory.OST_Ceilings,
											BuiltInCategory.OST_ShaftOpening,
											BuiltInCategory.OST_Walls,],
				'Код пакета работ': [
											BuiltInCategory.OST_Doors,
											BuiltInCategory.OST_StructuralFraming,
											BuiltInCategory.OST_Columns,
											BuiltInCategory.OST_Stairs,
											BuiltInCategory.OST_StructuralColumns,
											BuiltInCategory.OST_Windows,
											BuiltInCategory.OST_Ramps,
											BuiltInCategory.OST_Floors,
											BuiltInCategory.OST_Ceilings,
											BuiltInCategory.OST_ShaftOpening,
											BuiltInCategory.OST_Walls,],
				'Наименование пакета работ': [
											BuiltInCategory.OST_Doors,
											BuiltInCategory.OST_StructuralFraming,
											BuiltInCategory.OST_Columns,
											BuiltInCategory.OST_Stairs,
											BuiltInCategory.OST_StructuralColumns,
											BuiltInCategory.OST_Windows,
											BuiltInCategory.OST_Ramps,
											BuiltInCategory.OST_Floors,
											BuiltInCategory.OST_Ceilings,
											BuiltInCategory.OST_ShaftOpening,
											BuiltInCategory.OST_Walls,],
				'Код статьи затрат': [
											BuiltInCategory.OST_Doors,
											BuiltInCategory.OST_StructuralFraming,
											BuiltInCategory.OST_Columns,
											BuiltInCategory.OST_Stairs,
											BuiltInCategory.OST_StructuralColumns,
											BuiltInCategory.OST_Windows,
											BuiltInCategory.OST_Ramps,
											BuiltInCategory.OST_Floors,
											BuiltInCategory.OST_Ceilings,
											BuiltInCategory.OST_ShaftOpening,
											BuiltInCategory.OST_Walls,],
				'Идентификатор зоны': [
											BuiltInCategory.OST_Doors,
											BuiltInCategory.OST_StructuralFraming,
											BuiltInCategory.OST_Columns,
											BuiltInCategory.OST_Stairs,
											BuiltInCategory.OST_StructuralColumns,
											BuiltInCategory.OST_Windows,
											BuiltInCategory.OST_Ramps,
											BuiltInCategory.OST_Floors,
											BuiltInCategory.OST_Ceilings,
											BuiltInCategory.OST_ShaftOpening,
											BuiltInCategory.OST_Walls,],
				'Наименование зоны': [
											BuiltInCategory.OST_Doors,
											BuiltInCategory.OST_StructuralFraming,
											BuiltInCategory.OST_Columns,
											BuiltInCategory.OST_Stairs,
											BuiltInCategory.OST_StructuralColumns,
											BuiltInCategory.OST_Windows,
											BuiltInCategory.OST_Ramps,
											BuiltInCategory.OST_Floors,
											BuiltInCategory.OST_Ceilings,
											BuiltInCategory.OST_ShaftOpening,
											BuiltInCategory.OST_Walls,],
				'Позиционное обозначение (тег)': [
											BuiltInCategory.OST_Doors,
											BuiltInCategory.OST_StructuralFraming,
											BuiltInCategory.OST_Columns,
											BuiltInCategory.OST_Stairs,
											BuiltInCategory.OST_StructuralColumns,
											BuiltInCategory.OST_Windows,
											BuiltInCategory.OST_Ramps,
											BuiltInCategory.OST_Floors,
											BuiltInCategory.OST_Ceilings,
											BuiltInCategory.OST_ShaftOpening,
											BuiltInCategory.OST_Walls,],
				'Идентификатор линии/участка': [
											BuiltInCategory.OST_Doors,
											BuiltInCategory.OST_StructuralFraming,
											BuiltInCategory.OST_Columns,
											BuiltInCategory.OST_Stairs,
											BuiltInCategory.OST_StructuralColumns,
											BuiltInCategory.OST_Windows,
											BuiltInCategory.OST_Ramps,
											BuiltInCategory.OST_Floors,
											BuiltInCategory.OST_Ceilings,
											BuiltInCategory.OST_ShaftOpening,
											BuiltInCategory.OST_Walls,],
				'Наименование линии/участка': [
											BuiltInCategory.OST_Doors,
											BuiltInCategory.OST_StructuralFraming,
											BuiltInCategory.OST_Columns,
											BuiltInCategory.OST_Stairs,
											BuiltInCategory.OST_StructuralColumns,
											BuiltInCategory.OST_Windows,
											BuiltInCategory.OST_Ramps,
											BuiltInCategory.OST_Floors,
											BuiltInCategory.OST_Ceilings,
											BuiltInCategory.OST_ShaftOpening,
											BuiltInCategory.OST_Walls,],
				'Код ТМЦ': [
											BuiltInCategory.OST_Doors,
											BuiltInCategory.OST_StructuralFraming,
											BuiltInCategory.OST_Columns,
											BuiltInCategory.OST_Stairs,
											BuiltInCategory.OST_StructuralColumns,
											BuiltInCategory.OST_Windows,
											BuiltInCategory.OST_Ramps,
											BuiltInCategory.OST_Floors,
											BuiltInCategory.OST_Ceilings,
											BuiltInCategory.OST_ShaftOpening,
											BuiltInCategory.OST_Walls,],
		},
		'KR': {
				'Идентификатор проекта':[BuiltInCategory.OST_ProjectInformation],
                'Наименование проекта':[BuiltInCategory.OST_ProjectInformation],
                'Идентификатор объекта':[BuiltInCategory.OST_ProjectInformation],
                'Наименование объекта':[BuiltInCategory.OST_ProjectInformation],
				'Идентификатор зоны работы': [
											BuiltInCategory.OST_StructuralFramingSystem,
											BuiltInCategory.OST_Stairs,
											BuiltInCategory.OST_Columns,
											BuiltInCategory.OST_StructuralColumns,
											BuiltInCategory.OST_Floors,
											BuiltInCategory.OST_StructuralFoundation,],
				'Наименование зоны работы': [
											BuiltInCategory.OST_StructuralFramingSystem,
											BuiltInCategory.OST_Stairs,
											BuiltInCategory.OST_Columns,
											BuiltInCategory.OST_StructuralColumns,
											BuiltInCategory.OST_Floors,
											BuiltInCategory.OST_StructuralFoundation,],
				'Идентификатор вида работ': [
											BuiltInCategory.OST_StructuralFramingSystem,
											BuiltInCategory.OST_Stairs,
											BuiltInCategory.OST_Columns,
											BuiltInCategory.OST_StructuralColumns,
											BuiltInCategory.OST_Floors,
											BuiltInCategory.OST_StructuralFoundation,],					
				'Наименование вида работ': [
											BuiltInCategory.OST_StructuralFramingSystem,
											BuiltInCategory.OST_Stairs,
											BuiltInCategory.OST_Columns,
											BuiltInCategory.OST_StructuralColumns,
											BuiltInCategory.OST_Floors,
											BuiltInCategory.OST_StructuralFoundation,],					
				'Идентификатор операции': [
											BuiltInCategory.OST_StructuralFramingSystem,
											BuiltInCategory.OST_Stairs,
											BuiltInCategory.OST_Columns,
											BuiltInCategory.OST_StructuralColumns,
											BuiltInCategory.OST_Floors,
											BuiltInCategory.OST_StructuralFoundation,],
				'Наименование операции': [
											BuiltInCategory.OST_StructuralFramingSystem,
											BuiltInCategory.OST_Stairs,
											BuiltInCategory.OST_Columns,
											BuiltInCategory.OST_StructuralColumns,
											BuiltInCategory.OST_Floors,
											BuiltInCategory.OST_StructuralFoundation,],
				'Код пакета работ': [
											BuiltInCategory.OST_StructuralFramingSystem,
											BuiltInCategory.OST_Stairs,
											BuiltInCategory.OST_Columns,
											BuiltInCategory.OST_StructuralColumns,
											BuiltInCategory.OST_Floors,
											BuiltInCategory.OST_StructuralFoundation,],
				'Наименование пакета работ': [
											BuiltInCategory.OST_StructuralFramingSystem,
											BuiltInCategory.OST_Stairs,
											BuiltInCategory.OST_Columns,
											BuiltInCategory.OST_StructuralColumns,
											BuiltInCategory.OST_Floors,
											BuiltInCategory.OST_StructuralFoundation,],
				'Код статьи затрат': [
											BuiltInCategory.OST_StructuralFramingSystem,
											BuiltInCategory.OST_Stairs,
											BuiltInCategory.OST_Columns,
											BuiltInCategory.OST_StructuralColumns,
											BuiltInCategory.OST_Floors,
											BuiltInCategory.OST_StructuralFoundation,],
				'Идентификатор зоны': [
											BuiltInCategory.OST_StructuralFramingSystem,
											BuiltInCategory.OST_Stairs,
											BuiltInCategory.OST_Columns,
											BuiltInCategory.OST_StructuralColumns,
											BuiltInCategory.OST_Floors,
											BuiltInCategory.OST_StructuralFoundation,],
				'Наименование зоны': [
											BuiltInCategory.OST_StructuralFramingSystem,
											BuiltInCategory.OST_Stairs,
											BuiltInCategory.OST_Columns,
											BuiltInCategory.OST_StructuralColumns,
											BuiltInCategory.OST_Floors,
											BuiltInCategory.OST_StructuralFoundation,],
				'Позиционное обозначение (тег)': [
											BuiltInCategory.OST_StructuralFramingSystem,
											BuiltInCategory.OST_Stairs,
											BuiltInCategory.OST_Columns,
											BuiltInCategory.OST_StructuralColumns,
											BuiltInCategory.OST_Floors,
											BuiltInCategory.OST_StructuralFoundation,],
				'Идентификатор линии/участка': [
											BuiltInCategory.OST_StructuralFramingSystem,
											BuiltInCategory.OST_Stairs,
											BuiltInCategory.OST_Columns,
											BuiltInCategory.OST_StructuralColumns,
											BuiltInCategory.OST_Floors,
											BuiltInCategory.OST_StructuralFoundation,],
				'Наименование линии/участка': [
											BuiltInCategory.OST_StructuralFramingSystem,
											BuiltInCategory.OST_Stairs,
											BuiltInCategory.OST_Columns,
											BuiltInCategory.OST_StructuralColumns,
											BuiltInCategory.OST_Floors,
											BuiltInCategory.OST_StructuralFoundation,],
				'Код ТМЦ': [
											BuiltInCategory.OST_StructuralFramingSystem,
											BuiltInCategory.OST_Stairs,
											BuiltInCategory.OST_Columns,
											BuiltInCategory.OST_StructuralColumns,
											BuiltInCategory.OST_Floors,
											BuiltInCategory.OST_StructuralFoundation,],
		},
		'SS, EOM, EK, IVC, AEMK, AUGPT, ACU.ES, ИСВН, EP, АСПЗ, СС, ЭП': {
				'Идентификатор проекта':[BuiltInCategory.OST_ProjectInformation],
                'Наименование проекта':[BuiltInCategory.OST_ProjectInformation],
                'Идентификатор объекта':[BuiltInCategory.OST_ProjectInformation],
                'Наименование объекта':[BuiltInCategory.OST_ProjectInformation],
				'Идентификатор зоны работы': [
											BuiltInCategory.OST_LightingFixtures,
											BuiltInCategory.OST_DataDevices,											
											BuiltInCategory.OST_CableTray,
											BuiltInCategory.OST_Conduit,
											BuiltInCategory.OST_FireAlarmDevices,
											BuiltInCategory.OST_LightingDevices,
                                        	BuiltInCategory.OST_CableTrayFitting,
											BuiltInCategory.OST_ConduitFitting,
											BuiltInCategory.OST_PipeCurves,
											BuiltInCategory.OST_ElectricalEquipment,],
				'Наименование зоны работы': [
											BuiltInCategory.OST_LightingFixtures,
											BuiltInCategory.OST_DataDevices,											
											BuiltInCategory.OST_CableTray,
											BuiltInCategory.OST_Conduit,
											BuiltInCategory.OST_FireAlarmDevices,
											BuiltInCategory.OST_LightingDevices,
                                        	BuiltInCategory.OST_CableTrayFitting,
											BuiltInCategory.OST_ConduitFitting,
											BuiltInCategory.OST_PipeCurves,
											BuiltInCategory.OST_ElectricalEquipment,],				
				'Идентификатор вида работ': [
											BuiltInCategory.OST_StructuralFramingSystem,
											BuiltInCategory.OST_Stairs,
											BuiltInCategory.OST_Columns,
											BuiltInCategory.OST_StructuralColumns,
											BuiltInCategory.OST_Floors,
											BuiltInCategory.OST_StructuralFoundation,],					
				'Наименование вида работ': [
											BuiltInCategory.OST_StructuralFramingSystem,
											BuiltInCategory.OST_Stairs,
											BuiltInCategory.OST_Columns,
											BuiltInCategory.OST_StructuralColumns,
											BuiltInCategory.OST_Floors,
											BuiltInCategory.OST_StructuralFoundation,],					
				'Идентификатор операции': [
											BuiltInCategory.OST_LightingFixtures,
											BuiltInCategory.OST_DataDevices,											
											BuiltInCategory.OST_CableTray,
											BuiltInCategory.OST_Conduit,
											BuiltInCategory.OST_FireAlarmDevices,
											BuiltInCategory.OST_LightingDevices,
                                        	BuiltInCategory.OST_CableTrayFitting,
											BuiltInCategory.OST_ConduitFitting,
											BuiltInCategory.OST_PipeCurves,
											BuiltInCategory.OST_ElectricalEquipment,],				
				'Наименование операции': [
											BuiltInCategory.OST_LightingFixtures,
											BuiltInCategory.OST_DataDevices,											
											BuiltInCategory.OST_CableTray,
											BuiltInCategory.OST_Conduit,
											BuiltInCategory.OST_FireAlarmDevices,
											BuiltInCategory.OST_LightingDevices,
                                        	BuiltInCategory.OST_CableTrayFitting,
											BuiltInCategory.OST_ConduitFitting,
											BuiltInCategory.OST_PipeCurves,
											BuiltInCategory.OST_ElectricalEquipment,],				
				'Код пакета работ': [
											BuiltInCategory.OST_LightingFixtures,
											BuiltInCategory.OST_DataDevices,											
											BuiltInCategory.OST_CableTray,
											BuiltInCategory.OST_Conduit,
											BuiltInCategory.OST_FireAlarmDevices,
											BuiltInCategory.OST_LightingDevices,
                                        	BuiltInCategory.OST_CableTrayFitting,
											BuiltInCategory.OST_ConduitFitting,
											BuiltInCategory.OST_PipeCurves,
											BuiltInCategory.OST_ElectricalEquipment,],				
				'Наименование пакета работ': [
											BuiltInCategory.OST_LightingFixtures,
											BuiltInCategory.OST_DataDevices,											
											BuiltInCategory.OST_CableTray,
											BuiltInCategory.OST_Conduit,
											BuiltInCategory.OST_FireAlarmDevices,
											BuiltInCategory.OST_LightingDevices,
                                        	BuiltInCategory.OST_CableTrayFitting,
											BuiltInCategory.OST_ConduitFitting,
											BuiltInCategory.OST_PipeCurves,
											BuiltInCategory.OST_ElectricalEquipment,],				
				'Код статьи затрат': [
											BuiltInCategory.OST_LightingFixtures,
											BuiltInCategory.OST_DataDevices,											
											BuiltInCategory.OST_CableTray,
											BuiltInCategory.OST_Conduit,
											BuiltInCategory.OST_FireAlarmDevices,
											BuiltInCategory.OST_LightingDevices,
                                        	BuiltInCategory.OST_CableTrayFitting,
											BuiltInCategory.OST_ConduitFitting,
											BuiltInCategory.OST_PipeCurves,
											BuiltInCategory.OST_ElectricalEquipment,],				
				'Идентификатор зоны': [
											BuiltInCategory.OST_LightingFixtures,
											BuiltInCategory.OST_DataDevices,											
											BuiltInCategory.OST_CableTray,
											BuiltInCategory.OST_Conduit,
											BuiltInCategory.OST_FireAlarmDevices,
											BuiltInCategory.OST_LightingDevices,
                                        	BuiltInCategory.OST_CableTrayFitting,
											BuiltInCategory.OST_ConduitFitting,
											BuiltInCategory.OST_PipeCurves,
											BuiltInCategory.OST_ElectricalEquipment,],				
				'Наименование зоны': [
											BuiltInCategory.OST_LightingFixtures,
											BuiltInCategory.OST_DataDevices,											
											BuiltInCategory.OST_CableTray,
											BuiltInCategory.OST_Conduit,
											BuiltInCategory.OST_FireAlarmDevices,
											BuiltInCategory.OST_LightingDevices,
                                        	BuiltInCategory.OST_CableTrayFitting,
											BuiltInCategory.OST_ConduitFitting,
											BuiltInCategory.OST_PipeCurves,
											BuiltInCategory.OST_ElectricalEquipment,],				
				'Позиционное обозначение (тег)': [
											BuiltInCategory.OST_LightingFixtures,
											BuiltInCategory.OST_DataDevices,											
											BuiltInCategory.OST_CableTray,
											BuiltInCategory.OST_Conduit,
											BuiltInCategory.OST_FireAlarmDevices,
											BuiltInCategory.OST_LightingDevices,
                                        	BuiltInCategory.OST_CableTrayFitting,
											BuiltInCategory.OST_ConduitFitting,
											BuiltInCategory.OST_PipeCurves,
											BuiltInCategory.OST_ElectricalEquipment,],				
				'Идентификатор линии/участка': [
											BuiltInCategory.OST_LightingFixtures,
											BuiltInCategory.OST_DataDevices,											
											BuiltInCategory.OST_CableTray,
											BuiltInCategory.OST_Conduit,
											BuiltInCategory.OST_FireAlarmDevices,
											BuiltInCategory.OST_LightingDevices,
                                        	BuiltInCategory.OST_CableTrayFitting,
											BuiltInCategory.OST_ConduitFitting,
											BuiltInCategory.OST_PipeCurves,
											BuiltInCategory.OST_ElectricalEquipment,],				
				'Наименование линии/участка': [
											BuiltInCategory.OST_LightingFixtures,
											BuiltInCategory.OST_DataDevices,											
											BuiltInCategory.OST_CableTray,
											BuiltInCategory.OST_Conduit,
											BuiltInCategory.OST_FireAlarmDevices,
											BuiltInCategory.OST_LightingDevices,
                                        	BuiltInCategory.OST_CableTrayFitting,
											BuiltInCategory.OST_ConduitFitting,
											BuiltInCategory.OST_PipeCurves,
											BuiltInCategory.OST_ElectricalEquipment,],				
				'Код ТМЦ': [
											BuiltInCategory.OST_LightingFixtures,
											BuiltInCategory.OST_DataDevices,											
											BuiltInCategory.OST_CableTray,
											BuiltInCategory.OST_Conduit,
											BuiltInCategory.OST_FireAlarmDevices,
											BuiltInCategory.OST_LightingDevices,
                                        	BuiltInCategory.OST_CableTrayFitting,
											BuiltInCategory.OST_ConduitFitting,
											BuiltInCategory.OST_PipeCurves,
											BuiltInCategory.OST_ElectricalEquipment,],					
		},
}
